### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Midnighter** [bucknerns/versioneer-518#1]
Hi @bucknerns,

Thank you for creating this. It seems like a step in the right direction! Could you add a little more documentation, please, of how to use this now?

What I have tried is:

`pyproject.toml`
```ini
[build-system]
requires = [
  "setuptools>=40.6.0",
  "versioneer-518",
  "wheel"
]
```

I have removed `versioneer.py` and `src/mypackage/_version.py` from my project. Changed `src/mypackage/__init__.py` to:

```py
from versioneer import get_version

__version__ = get_version()
del get_version
```

which gives me the following error:

```
VersioneerBadRootError: Versioneer was unable to run the project root directory. Versioneer requires setup.py to be executed from its immediate directory (like 'python setup.py COMMAND'), or in a way that lets it use sys.argv[0] to find the root (like 'python path/to/setup.py COMMAND').
```

Since others say they have succeeded, I'm clearly doing something wrong.

**Comment by Midnighter** [comment]
Okay, I've made two changes:

1. Added the build backend to `pyproject.toml`

    ```
    build-backend = "setuptools.build_meta"
    ```

2. Changed back the `__init__.py` to:

    ```py
    from ._version import get_versions

    __version__ = get_versions()["version"]
    del get_versions
    ```

And now it works as expected when I run `pip install .`. However, for local development I often like to use `pip install -e .` which no longer works sadly.

**Comment by bucknerns** [comment]
Can you link your repo I think you may still have some issues, you shouldn't need that in the __init__.py.
Think I found it, https://github.com/Midnighter/dependency-info/pull/3

**Comment by Midnighter** [comment]
That's the one but let me push the branch that I'm working on for this.

**Comment by Midnighter** [comment]
I see you've opened a PR, amazing :heart:

**Comment by Midnighter** [comment]
It's a bit of a pity to lose the `__version__` attribute on the package but it's not a huge loss, I suppose.

May I suggest that you include a link to https://github.com/python-versioneer/example-518 in the readme (and on PyPI)?
