### ISSUE TITLE
What is the correct setup to create package distributions?

### ISSUE THREAD

**Issue by Midnighter** [bucknerns/versioneer-518#2]
My `setup.py` currently contains:

```py
import versioneer
from setuptools import setup


# All other arguments are defined in `setup.cfg`.
setup(version=versioneer.get_version(), cmdclass=versioneer.get_cmdclass())
```

Then I try to run `python setup.py sdist bdist_wheel` but I get a `ModuleNotFoundError` for versioneer. If I install `versioneer-518` in the environment, I get the following error:

```
UPDATING mypackage-1.0.0/src/mypackage/_version.py
error: [Errno 2] No such file or directory: 'mypackage-1.0.0/src/mypackage/_version.py'
```

How do I fix this in order to distribute my package?

I keep my versioneer configuration in `setup.cfg` which looks like:

```ini
[versioneer]
VCS = git
style = pep440
versionfile_source = src/mypackage/_version.py
versionfile_build = mypackage/_version.py
tag_prefix =
parentdir_prefix = mypackage-
```

**Comment by bucknerns** [comment]
I use a cookiecutter template that asks for these and creates a repo like the one [here](https://github.com/python-versioneer/example-518). You don't have to do a template but I recommend it. It should work just like the original except with the added pyproject.toml file. Also you need a version of pip that supports the pyproject.toml file(newer than apr 2018 version 10+).
The specific error is complaining you don't have the empty _version.py file. Versioneer will populate that file with static values when you create the wheel file. 

Example cookie cutter
```someuser@desktop:~/code/test$ cookiecutter cookiecutter-template/
full_name [Nathan Buckner]:   
email [example@gmail.com]: example@example.com
repo_name [myproject]: example
package [package]: examplepackage
project_short_description [Description]: SomeDescription
url [git@github.com:bucknerns/.git]: git@github.com:python-versioneer/example-518.git
Initialized empty Git repository in /home/nathan/code.work/test/example/.git/
[master (root-commit) 9d096fe] Cookiecutter Initial Commit
 12 files changed, 243 insertions(+)
 create mode 100644 .gitignore
 create mode 100644 MANIFEST.in
 create mode 100644 Makefile
 create mode 100644 README.rst
 create mode 100644 docs/conf.py
 create mode 100644 docs/index.rst
 create mode 100644 pyproject.toml
 create mode 100644 setup.cfg
 create mode 100644 setup.py
 create mode 100644 src/examplepackage/_example_version.py
 create mode 100644 tests/test_sample.py

```

Example static values
```
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-11T06:45:29-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "e282cf353bc24656d6b1ec67d9cbf4cda0f6c408",
 "version": "0+untagged.1.ge282cf3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)```

**Comment by Midnighter** [comment]
So basically the solution is to keep an empty `_version.py` module in the project?

**Comment by Midnighter** [comment]
Okay, I can confirm that this works. Thank you!

**Comment by Midnighter** [comment]
Actually, it only works when versioneer-518 is installed in the environment. Is that expected?

**Comment by bucknerns** [comment]
Not sure what you mean? Looking at the latest commit looks like tox is installing and passing on your pipeline and it installs locally without versioneer-518 using pip. It also passes the tox tests.

**Comment by Midnighter** [comment]
I mean, `python setup.py sdist bdist_wheel` only seems to work when I have versioneer-518 installed beforehand. I'm not sure why :confused:

**Comment by bucknerns** [comment]
This is because you should be using pip `pip wheel --no-deps --wheel-dir=dist .` which will look at the pyproject.toml.

**Comment by Midnighter** [comment]
I see. I also wanted a source distribution so I went with the suggestion provided [here on SO](https://stackoverflow.com/a/58756491). It requires me to install pep517 but overall it seems like the best solution.

```
python -m pep517.build --source --binary .
```

Thank you for your help. Truly appreciate the timely responses on a Sunday!
