### ISSUE TITLE
conda-forge

### ISSUE THREAD

**Issue by Midnighter** [bucknerns/versioneer-518#3]
Thanks again for all of your help yesterday. I was wondering if you are open to creating a conda-forge package for versioneer-518? (I'm also happy to create a PR for adding such to conda-forge.) As far as I can tell from my attempts in https://github.com/conda-forge/depinfo-feedstock/pull/3 PyPI is entirely disabled and thus versioneer-518 is required in the build step as a conda package.

**Comment by Midnighter** [comment]
In order to create a conda-forge package, it'd be much better to also have a source distribution of versioneer-518. At the moment this does not exist https://pypi.org/project/versioneer-518/#files. I'd be happy to create a pull request with GitHub actions for this if you like.

**Comment by Midnighter** [comment]
@bucknerns are you waiting on a decision about what will happen in https://github.com/python-versioneer/python-versioneer or is there some way I can assist making a decision on this issue?

**Comment by Midnighter** [comment]
Hi @bucknerns, Have you considered a conda-forge package release? Please let me know how I can help.

**Comment by bucknerns** [comment]
I haven't used conda-forge before so not sure what goes into making a package for it. If you have a script to publish it that just needs an account etc I don't make publishing it on updates.

**Comment by bucknerns** [comment]
@Midnighter I uploaded a sdist to pypi and looked up the process of making a recipe for conda-forge. I don't currently have time to make the recipe and submit the pull request but hopefully the sdist will unblock your ability to do it.

**Comment by Midnighter** [comment]
Awesome, thank you! That's great news. I will prepare a recipe for it. All I'd need you to do is to confirm that you want to be a maintainer of the conda recipe once the PR for it is open (I assume that you'd want to be a co-maintainer of it). I'll tag you when the time comes.

**Comment by Midnighter** [comment]
I've [opened a PR](https://github.com/conda-forge/staged-recipes/pull/14392) to add the conda-forge recipe. Please comment there @bucknerns that you agree to being a maintainer of the recipe.

While creating the recipe I also noticed that the source distribution does not bundle a license file. This is not a big deal but since conda-forge requires it, I have bundled the NIST public domain license with the recipe. Maybe that is something that needs correction.

**Comment by bucknerns** [comment]
Done

**Comment by Midnighter** [comment]
[This is now available](https://anaconda.org/conda-forge/versioneer-518). Thank you for your help 😊

**Comment by mdemoret-nv** [comment]
> [This is now available](https://anaconda.org/conda-forge/versioneer-518). Thank you for your help blush

Thanks for doing this. Adding `versioneer-518` to my conda build requirements worked like a charm.
